import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/style/globals.css";
import { LoadingProvider } from "@/context/LoadingContext";
import { LoadingScreen } from "@/stories/Organisms/LoadingScreen/LoadingScreen";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Adicione a meta tag diretamente aqui */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        {" "}
        <LoadingProvider>
          <LoadingScreen />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
